authors/urls.py
from django.urls import path
from . import views


app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'), 
    path('dashboard/recipe/new/', views.dashboard_recipe_new, name='dashboard_recipe_new'),
    path('dashboard/recipe/delete', views.dashboard_recipe_delete, name='dashboard_recipe_delete'),
    path(
        'dashboard/recipe/<int:id>/edit',
        views.DashboardRecipe.as_view(),
        name='dashboard_recipe_edit'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings #mesma coisa de from project import settings mas não é recomendado
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/search/', views.search, name='search'),
    path('recipes/category/<int:category_id>/', views.category, name='category'),
    path('recipes/<int:id>/', views.recipe, name='recipe'),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify #slugify cria uma slug a partir de um texto

# Create your models here.

class Category(models.Model):
    nome = models.CharField( max_length=65)

    def __str__(self):
        return self.nome
    

class Recipe(models.Model):
    title = models.CharField( max_length=65)
    description = models.CharField( max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='') #permitir envio sem imagem
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null = True,
        blank=True, default=None,
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null = True
        #on_delete: seta para null se a tabela Category for deletada
        #null = True: permite dado nulo dentro da tabela
    )

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('recipes:recipe', args = (self.id,))
    
    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.title)}'
            self.slug = slug

        return super().save(*args, **kwargs)

recipes/views.py
from django.http import Http404 
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.db.models import Q
from django.core.paginator import Paginator


from utils.recipes.factory import make_recipe
from utils.recipes.pagination import make_pagination_range
from .models import Recipe

# Create your views here.

def home(request):
    recipes = Recipe.objects.filter(
        is_published = True
    ).order_by('-id')

    try:
        current_page = int(request.GET.get('page', 1))
    except ValueError:
        current_page = 1
    
    #parte do paginator
    paginator = Paginator(recipes,2) #duas receitas por pagina
    page_obj = paginator.get_page(current_page)
    pagination_range = make_pagination_range(
        paginator.page_range,
        4,
        current_page
    )

    return render(request, 'recipes/pages/home.html', context={
        'recipes' : recipes,
        #'pagination_range': pagination_range
    })
#context adiciona dicionario aos templates
#utilizando looping para gerar 6 dados aleatórios dentro do dicionário recipes : [make_recipe() for _ in range(6)]

def category(request, category_id):
    recipes = Recipe.objects.filter(
        is_published = True,
        category__id = category_id #category__id acessa a tabela category a partir da foreign key na tabela recipe em busca do id
    ).order_by('-id')

    if not recipes:
        raise Http404('Category not found')

    return render(request, 'recipes/pages/category.html', context={
        'recipes' : recipes,
        'title' : f'{recipes.first().category.nome} - Category |',
    })


def recipe(request, id):
    recipe = Recipe.objects.filter(
        is_published = True,
        id = id 
    ).order_by('-id').first()

    #outra maneira de fazer sem ser consulta a mão: utilizando django shortcuts
    #recipe = get_object_or_404(Recipe, pk=id, is_published=True,)

    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe' : recipe,
        'is_detail_page': True,                                                                      
    })

def search(request):
    #pegando termo do input no html
    search_term = request.GET.get('q', '').strip() 

    if not search_term:
        raise Http404()
    
    #mostrar receitas baseadas no search_term
    recipes = Recipe.objects.filter(
        Q(title__icontains = search_term) | Q(description__icontains = search_term),
        is_published = True,
    ).order_by('-id')
    
    
    return render(request, 'recipes/pages/search.html', context={
        'page_title': f'Search for {search_term}',
        'recipes':recipes,
    })

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %} 
        <div class="recipe-cover">
            <img src="{{recipe.cover.url}}" alt="Temporário">
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

    <div class="recipe-author">
        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name}} {{ recipe.author.last_name}} 
                {% else %}
                    {{ recipe.author.username}}
                {% endif %}
            </span>
        {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at|date:"d/m/Y"}}
        </span>
        
        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span> {{ recipe.category.nome }} </span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>
            {{recipe.description}}
        </p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True%}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href=" {% url 'recipes:recipe' recipe.id %} ">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %} <!-- mostrar texto que possui codigo html-->
                {{recipe.preparation_steps|safe}}
             {% else %}
                {{recipe.preparation_steps|linebreaksbr}}
            {% endif %}
        </div>
    {% endif %}
    

</div>