authors/urls.py
from django.urls import path
from . import views


app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'), 
    path('dashboard/recipe/new/', views.dashboard_recipe_new, name='dashboard_recipe_new'),
    path('dashboard/recipe/delete', views.dashboard_recipe_delete, name='dashboard_recipe_delete'),
    path(
        'dashboard/recipe/<int:id>/edit',
        views.DashboardRecipe.as_view(),
        name='dashboard_recipe_edit'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings #mesma coisa de from project import settings mas não é recomendado
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

authors/models.py
from django.db import models

# Create your models here.

authors/forms.py
from collections import defaultdict

from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from recipes.models import Recipe

class RegisterForm(forms.ModelForm):
    class Meta:
        #Modelo base
        model = User

        #Campos que estarão no form
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]
        # exclude = ['first_name']

        labels = {
            'first_name': 'First name',
            'last_name': 'Last name',
            'username': 'Username',
            'email': 'Email',
            'password': 'Password',

        }

        widgets = {
            'first_name': forms.TextInput(attrs={
                'placeholder':'Type your first name here'
            }),
            'last_name': forms.TextInput(attrs={
                'placeholder':'Type your last name here'
            }),
            'username': forms.TextInput(attrs={
                'placeholder':'Type your username here'
            }),
            'email': forms.TextInput(attrs={
                'placeholder':'Type your email here'
            }),
            'password': forms.PasswordInput(attrs={
                'placeholder':'Type your password here'
            }),
        }

    #validar emails diferentes no cadastro
    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        exists = User.objects.filter(email=email).exists()
        
        if exists:
            raise ValidationError(
                'User e-mail is already in use', code ='invalid',
            )

        return email
    
class loginForm(forms.Form):
    username = forms.CharField(
        widget = forms.TextInput(attrs={
                'placeholder':'Type your  username here'
        }),
    )
    password = forms.CharField(
        widget= forms.PasswordInput(attrs={
            'placeholder':'Type your password here'  
        })
    )

class AuthorRecipeForm(forms.ModelForm):
    def __init(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list) #util para o metodo clean para validacao do formulario

    class Meta:
        model = Recipe
        fields = ['title', 'description', 'preparation_time', 
                  'preparation_time_unit', 'servings','servings_unit', 
                  'preparation_steps', 'cover'
                ]
        widgets = {
            'cover': forms.FileInput(
                attrs={
                    'class': 'span-2'
                }
            ),
            'servings_unit': forms.Select(
                choices=(
                    ('Porções', 'Porções'),
                    ('Pedaços', 'Pedaços'),
                    ('Pessoas', 'Pessoas'),
                ),
            ),
            'preparation_time_unit': forms.Select(
                choices=(
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                ),
            ),
        }

        def clean(self, *args, **kwargs):
            super_clean = super().clean(*args, **kwargs)
            cleaned_data = self.cleaned_data

            title = cleaned_data.get('title')
            description = cleaned_data.get('description')

            if len(title) < 5:
                self._my_errors['title'].append('Must have at least 5 chars.')

            if title == description:
                self._my_errors['title'].append('Cannot be equal to description')




            if self._my_errors: #mostrar erros na tela
                raise ValidationError(self._my_errors)

            return super_clean

authors/views/all.py
from django.shortcuts import render, redirect
from django.http import Http404
from authors.forms import loginForm, RegisterForm
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout #aut checa se o usuario vai ou nao autenticar e login de fato loga no sistema   
from django.contrib.auth.decorators import login_required
from recipes.models import Recipe
from authors.forms import AuthorRecipeForm

# Create your views here.
def register_view(request):
    register_form_data = request.session.get('register_form_data', None)

    form = RegisterForm(register_form_data)
    return render(request, 'authors/pages/register_view.html', context={
        'form': form,
        'form_action': reverse('authors:register_create'),
    })

def register_create(request):
    
    if not request.POST:
        raise Http404()
    
    
    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)

    #adicionando os dados na base de dados:
    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password) #salvando corretamente a senha na base de dados (criptografia)
        user.save()
        messages.success(request, 'Your user is created, please log in')

        #apagando dados da sessao
        del(request.session['register_form_data'])

    return redirect ('authors:login')

def login_view(request):
    form = loginForm()
    return render(request, 'authors/pages/login.html', context={
        'form': form,
        'form_action': reverse('authors:login_create'),

    })

def login_create(request):
    if not request.POST:
        raise Http404()

    form = loginForm(request.POST)
    login_url = reverse('authors:login')

    if form.is_valid():
        authenticated_user = authenticate(
            username = form.cleaned_data.get('username', ''),
            password = form.cleaned_data.get('password', '')
        )
        if authenticated_user is not None:
            messages.success(request, 'Logged in sucessfully')
            login(request, authenticated_user)
        
    return redirect(reverse('authors:dashboard'))


@login_required(login_url='authors:login', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        return redirect(reverse('authors:login'))

    if request.POST.get('username') != request.user.username:
        return redirect(reverse('authors:login'))

    logout(request)
    return redirect(reverse('authors:login'))

@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard(request):
    recipes = Recipe.objects.filter(
        is_published = False,
        author = request.user,
    )
    return render(request, 'authors/pages/dashboard.html', context= {
        'recipes': recipes
    })

@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_edit(request, id):
    recipe = Recipe.objects.filter(
        is_published = False,
        author = request.user,
        pk=id,
    ).first()

    if not recipe:
        raise Http404()
    
    form = AuthorRecipeForm(
        data = request.POST or None, 
        files=request.FILES or None,
        instance=recipe
    )

    if form.is_valid():
        #agora form é valido e posso tentar salvar
        recipe = form.save(commit=False) #salva o formulario em recipe
        recipe.author = request.user
        recipe.preparation_steps_is_html = False
        recipe.is_published = False 

        recipe.save() #salvando na base de dados
        messages.success(request, 'Sua receita foi salva com sucesso')
        return redirect(reverse('authors:dashboard_recipe_edit', args=(id,)))

    return render(request, 'authors/pages/dashboard_recipe.html', context= {
        'form': form,
    })

@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_new(request):

    form = AuthorRecipeForm(        
        data = request.POST or None, # é usado para passar os dados recebidos de uma solicitação HTTP para o formulário
        files=request.FILES or None, #é usado para passar os arquivos enviados pelo usuário
    )

    if form.is_valid():
        recipe = form.save(commit=False) #salva o formulario em recipe
        recipe.author = request.user
        recipe.preparation_steps_is_html = False
        recipe.is_published = False 

        recipe.save() #salvando na base de dados
        messages.success(request, 'Sua receita foi criada com sucesso')
        return redirect(reverse('authors:dashboard'))

    return render(request, 'authors/pages/dashboard_recipe_new.html', context= {
        'form': form,
    })  

@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_delete(request):
    if not request.POST:
        raise Http404()
    
    #a pessoa nao entra diretamente no link 
    POST = request.POST
    id = POST.get('id') 
    
    recipe = Recipe.objects.filter(
        is_published = False,
        author = request.user,
        pk=id,
        
    ).first()

    if not recipe:
        raise Http404()
    
    recipe.delete()
    messages.success(request,'Deleted sucessfully.')
    return redirect(reverse('authors:dashboard'))

authors/views/dashboard_recipe.py
from django.http.response import Http404
from django.views import View
from django.contrib import messages
from authors.forms import AuthorRecipeForm
from recipes.models import Recipe
from django.shortcuts import redirect, render
from django.urls import reverse


class DashboardRecipe(View): #fazendo por class based views a funcao dashboard_recipe_edit
    def get_recipe(self, id):
        recipe = None

        if id:
            recipe = Recipe.objects.filter(
                is_published = False,
                author = self.request.user,
                pk=id,
            ).first()

            if not recipe:
                raise Http404()
        
        return recipe;
    
    def render_recipe(self, form):
        return render(self.request, 'authors/pages/dashboard_recipe.html', context= {
            'form': form,
        })


    def get(self, request, id):
        recipe = self.get_recipe(id)
        form = AuthorRecipeForm(instance=recipe)
        return self.render_recipe(form)

    
    def Post(self, request, id):
        recipe = self.get_recipe(id);
        
        form = AuthorRecipeForm(
            data = request.POST or None, 
            files=request.FILES or None,
        )

        if form.is_valid():
            #agora form é valido e posso tentar salvar
            recipe = form.save(commit=False) #salva o formulario em recipe
            recipe.author = request.user
            recipe.preparation_steps_is_html = False
            recipe.is_published = False 

            recipe.save() #salvando na base de dados
            messages.success(request, 'Sua receita foi salva com sucesso')
            return redirect(reverse('authors:dashboard_recipe_edit', args=(id,)))


    
        return self.render_recipe(form)

authors/templates/authors/pages/dashboard.html
{% extends 'global/base.html' %}

{% block title %}Dashboard | {% endblock title %}

{% block content %}

    <div class="main-content center container">
        <h2>Dashboard ({{ user }})</h2>

        {% if messages %}
        <ul class="message-success">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <p>
          <form class="inline-form" action="{% url 'authors:logout' %}" method='POST'>
            {% csrf_token %}
            You are logged in with {{ request.user.username }}. 
            <a class="plaintext-button" href="{% url 'authors:dashboard' %}" >See your recipes</a>, 
            <a class="plaintext-button" href="{% url 'authors:dashboard_recipe_new'%}">create a new recipe</a> or 
            <input type="hidden" name="username" value="{{ request.user.username }}">
            <button class="plaintext-button" type="submit">click here</button> to logout.
          </form> 
        </p>      

        <div class="authors-dashboard-container">
            <h3>Your recipes</h3>
            <ul>
              {% for recipe in recipes %}
              <li>
                <a class="plaintext-button" href="{% url 'authors:dashboard_recipe_edit' recipe.id %}">{{recipe.title}}</a>

                <form class="inline-form form-delete" action="{% url 'authors:dashboard_recipe_delete' %}" method='POST'> - 
                  {% csrf_token %}
                  <input type="hidden" name="id" value="{{recipe.id}}">
                  <button class="plaintext-button" type="submit">❌</button>
                </form>
              </li>
              {%empty%}
              <li>
                <p>You do not have recipes, please create one</p>
              </li>
              {% endfor %}
            </ul>
        </div>

      </div>

{% endblock content %}

authors/templates/authors/pages/dashboard_recipe.html
{% extends 'global/base.html' %}

{% block title %}Dashboard Recipe | {% endblock title %}

{% block content %}

    <div class="main-content center container">
        <h2>Dashboard recipe</h2>
        
        {% if messages %}
        <ul class="message-success">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="left">
          {% include 'global/partials/form.html' %}
        </div>
    </div>

{% endblock content %}

authors/templates/authors/pages/dashboard_recipe_new.html
{% extends 'global/base.html' %}

{% block title %}Register Recipe | {% endblock title %}

{% block content %}

    <div class="main-content center container">
        <h2>Register recipe</h2>
        
        {% if messages %}
        <ul class="message-success">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="left">
          {% include 'global/partials/form.html' %}
        </div>
    </div>

{% endblock content %}

authors/templates/authors/pages/login.html
{% extends 'global/base.html' %}

{% block title %}Login | {% endblock title %}

{% block content %}

    {% if messages %}
    <ul class="message-success">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="main-content center container">                                                                             
        <h2>Login</h2>
        {% if user.is_authenticated %}
        <p>
            You are logged in with 
            {{ request.user.username }}. 
            Please, 
            <form class="inline-form" action="{% url 'authors:logout' %}" method='POST'>
              {% csrf_token %}
              <input type="hidden" name="username" value="{{ request.user.username }}">
              <button class="plaintext-button" type="submit">click here</button>
            </form> to logout.
          </div>
        {% endif %}
      </div>
    {% if not user.is_authenticated %}
      {% include 'global/partials/form.html' %}
    {% endif %}
    
{% endblock content %}

authors/templates/authors/pages/register_view.html
{% extends 'global/base.html' %}

{% block title %}Register | {% endblock title %}

{% block content %}

    {% if messages %}
    <ul class="message-success">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="main-content center container">
        <h2>Register {{ request.session.number }}</h2>
    </div>
    {% include 'global/partials/form.html' %}
    
{% endblock content %}